version: "3"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.15
    restart: always
    networks:
      - iot

  telegraf:
    container_name: telegraf
    image: telegraf:1.22.1
    restart: always
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot

  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    restart: always
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=admin-user
      - INFLUXDB_ADMIN_PASSWORD=telegraf-admin-password
      - INFLUXDB_USER=telegraf-username
      - INFLUXDB_PASSWORD=telegraf-password
    networks:
      - iot
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  grafana:
    container_name: grafana
    image: grafana/grafana:8.5.0
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

networks:
  iot:

volumes:
  influxdb-data:
  grafana-data: